### ISSUE TITLE
[todo] : 개발 진행 사항

### ISSUE THREAD

**Issue by CoffeeShelter** [CoffeeShelter/yagnawa#1]
### 데이터베이스
- [x] 건강기능식품 raw 테이블 구축
- [ ] 인증마크 정보 테이블 구축
- [ ] 가공된 건강기능식품 테이블 구축

### Rest API
- [ ] 단일 상품 조회
- [ ] 상품 목록 조회

### Utils
- [ ] 건강기능식품 정보 가공
- [ ] 건강기능식품 인증마크 탐지

### 화면
- [x] 시작 화면
- [x] 상품 리스트 화면
- [ ] 상품 정보 화면
- [ ] 상품 선택 화면
- [ ] 상품 이미지 편집 화면
